<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta content="en-us" http-equiv="Content-Language" />
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    <title>TicketWire</title>
	<link rel="stylesheet" href="core.css">
</head>

<body>
<div class="loginFormDiv">
    <form action="index.php" method="post" class="loginForm">
        <label id="Welcome">Welcome to TicketWire!</label><br/><br/>
        <input placeholder="Email" name="user" type="text" autofocus /><br /><br/>
        <input placeholder="Password" name="pass" type="password" /><br/><br/>
        <input name="submit" type="submit" value="submit" /><br /><br/>
        <a href="https://www.facebook.com/CRMBeesley" target="_blank">Forgot Password?</a>
    </form>
</div>
</body>

</html>